SELECT m.ID AS "가게 ID", m.NAME AS NAME, COUNT(u.ID) AS "결제 횟수"
FROM MERCHANTS m JOIN CARD_USAGES u ON m.ID = u.MERCHANT_ID
WHERE(m.NAME LIKE '%강남%' OR m.NAME LIKE '%논현%') AND u.CATEGORY = 0
GROUP by m.ID, m.NAME
ORDER by m.ID ASC;