WITH CARLOS_POINT as(
    SELECT X AS CAR_X, Y AS CAR_Y FROM HOUSE_LOCATIONS WHERE OWNER = 'Carlos'
),
CALCULATED_DISTANCE as(
    SELECT OWNER, ABS(X - CAR_X) + ABS(Y - CAR_Y) AS DISTANCE
    FROM HOUSE_LOCATIONS CROSS JOIN CARLOS_POINT
    WHERE OWNER != 'Carlos'
)

SELECT OWNER, DISTANCE
FROM CALCULATED_DISTANCE
WHERE DISTANCE = (SELECT MAX(DISTANCE) FROM CALCULATED_DISTANCE)
ORDER BY OWNER